#Get route call from browser

### GET All Person

GET http://localhost:8080/api/person
Accept: application/json

### GET Person

GET http://localhost:8080/api/person/P0002
Accept: application/json


### CREATE Person

POST http://localhost:8080/api/person
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "id": "P0003",
  "firstName": "Rotua",
  "lastName": "Nababan",
  "age": 20
}


### UPDATE Person

PUT http://localhost:8080/api/person/P0002
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "Ucok",
  "lastName": "Situngkir",
  "age": 22
}

### DELETE Person

DELETE http://localhost:8080/api/person/P0001
Authorization: Bearer {{auth_token}}
Accept: application/json


### LOGIN User

POST http://localhost:8080/api/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.data.accessToken); %}